<?php

namespace App\Enums;

enum BasicInfoErrorEnum: string
{
    case REQUIRED = 'REQUIRED';
    case INVALID_FORMAT = 'INVALID_FORMAT';
    case INVALID_VALUE = 'INVALID_VALUE';
    case INVALID_CATEGORY = 'INVALID_CATEGORY';
    case INVALID_PRODUCT_NAME = 'INVALID_PRODUCT_NAME';
    case ALREADY_EXISTS = 'ALREADY_EXISTS';
    case TOO_LONG = 'TOO_LONG';
    case TOO_SHORT = 'TOO_SHORT';
    case INVALID_SPEC_NUMBER = 'INVALID_SPEC_NUMBER';
    case INVALID_ARTICLE_CODE = 'INVALID_ARTICLE_CODE';
    case INVALID_COLOR = 'INVALID_COLOR';
    case INVALID_SIZE = 'INVALID_SIZE';
}
