<?php

namespace App\Enums;

enum MeasurementPointErrorEnum: string
{
    case REQUIRED = 'REQUIRED';
    case INVALID_NAME = 'INVALID_NAME';
    case INVALID_FORMAT = 'INVALID_FORMAT';
    case INVALID_FORMULA = 'INVALID_FORMULA';
    case NOT_FOUND = 'NOT_FOUND';
    case DUPLICATE = 'DUPLICATE';
    case LOGICAL_CONFLICT = 'LOGICAL_CONFLICT';
    case OUT_OF_RANGE = 'OUT_OF_RANGE';
    case MISSING_DEPENDENCY = 'MISSING_DEPENDENCY';
    case CIRCULAR_DEPENDENCY = 'CIRCULAR_DEPENDENCY';
    case INVALID_TYPE = 'INVALID_TYPE';
    case INVALID_SOURCE = 'INVALID_SOURCE';
    case INVALID_NATURE = 'INVALID_NATURE';
    case INVALID_EVALUATION_TYPE = 'INVALID_EVALUATION_TYPE';
    case MISSING_CONFIGURATION = 'MISSING_CONFIGURATION';
    case INVALID_RULE = 'INVALID_RULE';
    case INVALID_TOLERANCE = 'INVALID_TOLERANCE';
    case INVALID_SAMPLE_AMOUNT = 'INVALID_SAMPLE_AMOUNT';
    case SPECIAL_CHARACTER = 'SPECIAL_CHARACTER';
    case CONTAINS_SPACE = 'CONTAINS_SPACE';
    case UPPERCASE_NOT_ALLOWED = 'UPPERCASE_NOT_ALLOWED';
}
